name: Configure Environment
description: Configures the environment, downloads go.mod, and installs tools

inputs:
  region:
    description: "Deployment Region"
    required: true
  role:
    description: "IAM Role to assume"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      shell: bash
    - run: cd iac && npm i -g cdk
      shell: bash
    - run: cd iac && npm i
      shell: bash
    - name: Configure Git and Dependencies
      run: make configure
      shell: bash
    - name: Configure AWS Credentials
      id: creds
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.region }}
        role-to-assume: ${{ inputs.role }}